--[[
██████╗  █████╗     ██████╗ ███████╗██╗   ██╗███████╗██╗      ██████╗ ██████╗ ███████╗██████╗ 
██╔══██╗██╔══██╗    ██╔══██╗██╔════╝██║   ██║██╔════╝██║     ██╔═══██╗██╔══██╗██╔════╝██╔══██╗
██║  ██║╚██████║    ██║  ██║█████╗  ██║   ██║█████╗  ██║     ██║   ██║██████╔╝█████╗  ██████╔╝
██║  ██║ ╚═══██║    ██║  ██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██║     ██║   ██║██╔═══╝ ██╔══╝  ██╔══██╗
██████╔╝ █████╔╝    ██████╔╝███████╗ ╚████╔╝ ███████╗███████╗╚██████╔╝██║     ███████╗██║  ██║
╚═════╝  ╚════╝     ╚═════╝ ╚══════╝  ╚═══╝  ╚══════╝╚══════╝ ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═╝

Made by D9_Dev
]]

--- @class ConfigType
--- @field Debug boolean เปิด/ปิดโหมดดีบัก
--- @field OpenControl number ปุ่มเปิดอินเวนทอรี (KeyCode)
--- @field ExcludeAccountsList string[] รายชื่อบัญชีที่ไม่รวม
--- @field DistanceGive number ระยะทางสูงสุดในการให้ของ
--- @field blocktypeonallcategory table<string, boolean> ประเภทที่บล็อคในทุกหมวดหมู่
--- @field Category table<string, string[]> หมวดหมู่ไอเทม

--- @type ConfigType
Config = {}

Config.Debug = false

Config.OpenControl = 245 -- F2

-- จำนวนช่อง Fast Slot ที่แสดงใน NUI
Config.MaxFastslot = 7

--- @type string[]
Config.ExcludeAccountsList = {
    'bank'
}

Config.DistanceGive = 3.0 -- ระยะในการให้ของ

--- @type table<string, boolean>
Config.blocktypeonallcategory = {
	fashion = true,
	skinweapon = true,
	key = true,
}

Config.CarWelFare = { -- รถที่ให้เทรดผ่านบัตร Trade Car Welfare
	['toros'] = true,
	['thrax'] = true,
}

--- @type table<number, {key: string, label: string}>
Config.CategoryLabel = {
	[1] = {
		key = 'all',
		label = 'ALL',
	},
	[2] = {
		key = 'food',
		label = 'FOOD',
	},
	[3] = {
		key = 'weapon',
		label = 'WEAPON',
	},
	[4] = {
		key = 'fashion',
		label = 'FASHION',
	},
	[5] = {
		key = 'skinweapon',
		label = 'SKIN',
	},
	[6] = {
		key = 'key',
		label = 'VEHICLE',
	},
}

--- @class CategoryType
--- @field food string[] รายการไอเทมหมวดอาหาร
--- @field weapon string[] รายการไอเทมหมวดอาวุธ
--- @field accessory string[] รายการไอเทมหมวดเครื่องประดับ
Config.Category = {
	accessory = {
	},
	food = {
		"ramen",
		"happymeal",
		"tonkatsu",
		"mre",
		"milkshake",
		"coke",
		"burger",
		"ducknoodles",
	},
	weapon = {
		"WEAPON_UNARMED",
		"WEAPON_NIGHTSTICK",
		"WEAPON_SWITCHBLADE",
		"WEAPON_POOLCUE_0",
		"WEAPON_POOLCUE_1",
		"WEAPON_POOLCUE_EXTRA",
		"WEAPON_POOLCUE",
		"WEAPON_BOTTLE_0",
		"WEAPON_BOTTLE_1",
		"WEAPON_BOTTLE_2",
		"WEAPON_BOTTLE_EXTRA",
		"WEAPON_BOTTLE",
		"WEAPON_KNUCKLE_1",
		"WEAPON_KNUCKLE_2",
		"WEAPON_KNUCKLE_3",
		"WEAPON_KNUCKLE_EXTRA",
		"WEAPON_KNUCKLE",
	},
	skinweapon = {
		-- WEAPON_BOTTLE
		"skin_babythree_bottle",
		"skin_sweet_bottle",
		"skin_meaow_bottle",
		"skin_dimoo_bottle",
		"skin_honeybear_bottle",
		"skin_rich_bottle",
		"skin_summer_bottle",
		"skin_toothless_bottle",
		"skin_stitch_bottle",
		"skin_piggy_bottle",
		"skin_ducky_bottle",
		"skin_snow_bottle",
		"skin_winterfrost_black_bottle",
		"skin_winterfrost_white_bottle",
		"skin_shark_bottle",
		"skin_poker_bottle",
		"skin_melody_bottle",
		"skin_savage_bottle",
		
		-- WEAPON_KNUCKLE
		"skin_babythree_knukle",
		"skin_sweet_knuckle",
		"skin_meaow_knuckle",
		"skin_dimoo_knuckle",
		"skin_honeybear_knuckle",
		"skin_rich_knuckle",
		"skin_summer_knuckle",
		"skin_toothless_knuckle",
		"skin_stitch_knuckle",
		"skin_ducky_knuckle",
		"skin_snow_knuckle",
		"skin_winterfrost_black_knuckle",
		"skin_winterfrost_white_knuckle",
		"skin_poker_knuckle",
		"skin_melody_knuckle",
		"skin_savage_knuckle",
		
		-- WEAPON_POOLCUE
		"skin_babythree_poolcue",
		"skin_volt_poolcue",
		"skin_sweet_poolcue",
		"skin_meaow_poolcue",
		"skin_dimoo_poolcue",
		"skin_rich_poolcue",
		"skin_summer_poolcue",
		"skin_toothless_poolcue",
		"skin_stitch_poolcue",
		"skin_piggy_poolcue",
		"skin_ducky_poolcue",
		"skin_snow_poolcue",
		"skin_winterfrost_black_poolcue",
		"skin_winterfrost_white_poolcue",
		"skin_shark_poolcue",
		"skin_poker_poolcue",
		"skin_melody_poolcue",
		"skin_savage_poolcue",
	},
	fashion = {
		'coolkids_bbt_bear',
		'coolkids_bbt_elephant',
		'coolkids_bbt_fox',
		'coolkids_bbt_goat',
		'coolkids_bbt_rabbit',
		'coolkids_bbt_panda',
		'coolkids_bbt_pig',
		'MagicCircle_BabyThree',
		'admin_armband',
		'council_armband',
		'medic_armband',
		'newplayer_armband',
		'police_armband',
		'protect_armband',
		'serverboost_armband',
		'story_armband',
		'streamer_armband',
		'beginer_armband',
		'777_cammyui1',
		'777_cammyui2',
		'777_cammyui3',
		'777_cammyui4',
		'777_cammyui5',
		'777_cammyui6',
		'777_cammyui7',
		'pikaboo_sanrio_bunny_cinnamoroll',
		'pikaboo_sanrio_bunny_kuromi',
		'pikaboo_sanrio_bunny_kitty',
		'pikaboo_sanrio_bunny_mymelody',
		'pikaboo_sanrio_bunny_pompompurin',
		'pikaboo_sanrio_bunny_pochacco',
		'ring_happy',
		'galaxyteddy1',
		'galaxyteddy2',
		'galaxyteddy3',
		'galaxyteddy4',
		'galaxyteddy5',
		'galaxyteddy6',
		'meow_mymelody_cake01',
		'meow_mymelody_cake02',
		'meow_mymelody_cake03',
		'meow_mymelody_cake04',
		'meow_mymelody_cake05',
		'ax_babyminnie',
		'ax_mickeyballoon',
		'ax_daisysweet',
		'ax_littlestar',
		'ax_popcornduckling',
		'ax_sleepychipmunk',
		'pikaboo_dino_camp_forest_glow',
		'pikaboo_dino_camp_butterfly_catcher',
		'pikaboo_dino_camp_bee',
		'pikaboo_dino_camp_camera',
		'pikaboo_dino_camp_map',
		'pikaboo_dino_camp_marshmallow',
		'pikaboo_dino_camp_mushroom',
		'kw_agencythree_a',
		'kw_agencythree_d',
		'kw_agencythree_g',
		'kw_agencythree_h',
		'kw_frontbadtwo_a',
		'kw_frontbadtwo_i',
		'kw_frontbadtwo_j',
		'kw_frontbad_f',
		'kw_frontnaka_a',
		'kw_frontnaka_b',
		'kw_frontnaka_c',
		'kw_frontnaka_g',
		'kw_frontnaka_i',
		'kw_favfront_a',
		'kw_fronting_a',
		'kw_fronting_b',
		'kw_esanfrontone_a',
		'kw_esanfrontone_h',
		'kw_esanfrontone_i',
		'kw_thaiwordtwo_e',
		'kw_thaiwordtwo_f',
		'kw_thaiwordtwo_i',
		'kw_frontsad_h',
		'kw_front_agency_d',
		'kw_front_agency_e',
		'kw_frontnarak_i',
		'kw_frontcutemak_g',
		'kw_fronthit_a',
		'kw_thaiwordone_h',
		'kw_thaiwordone_i',
		'kw_newbie_nightown',
		'bbg_ui85_1',
		'bbg_ui85_2',
		'bbg_ui85_3',
		'bbg_ui85_4',
		'pikaboo_pooh_bee',
		'pikaboo_pooh_popcorn',
		'pikaboo_pooh_pigletcar',
		'pikaboo_pooh_scooter',
		'pikaboo_pooh_balloon',
		'pikaboo_pooh_honeyback',
		'bbg_ui75_1',
		'bbg_ui75_2',
		'bbg_ui75_3',
		'bbg_ui75_4',
		'bbg_ui75_5',
		'bbg_ui74_1',
		'bbg_ui74_2',
		'bbg_ui74_3',
		'bbg_ui74_4',
		'pikaboo_keroduck_rainy_time_coaty',
		'pikaboo_keroduck_rainy_time_rain_doll',
		'pikaboo_keroduck_rainy_time_rainy_parade',
		'pikaboo_keroduck_rainy_time_leafy',
		'pikaboo_keroduck_rainy_time_cloudy',
		'pikaboo_keroduck_rainy_time_brella',
		'pikaboo_happy1stanv_teddy_pop',
		'pikaboo_happy1stanv_teddy_gift',
		'pikaboo_happy1stanv_teddy_cake',
		'pikaboo_happy1stanv_teddy_confetti',
		'bbg_ui69_1',
		'bbg_ui69_2',
		'bbg_ui69_3',
		'bbg_ui69_4',
		'bbg_ui69_5',
		'bbg_ui69_6',
		'meow_valentine2_cat01',
		'meow_valentine2_silk',
		'meow_valentine2_cat02',
		'meow_valentine2_cat03',
		'meow_valentine2_cat04',
		'meow_valentine2_kitkat01',
		'wing_blade',
		'wing_celestial',
		'wing_chada',
		'wing_crystal',
		'wing_devileye',
		'wing_dragonhalf',
		'wing_godeye',
		'wing_wolfice',
		'catbox',
		'cows3',
		'shibadikdik1',
		'shibadikdik2',
		'shibadikdik3',
		'luxe_ghost_fashion',
		'bat_halloween',
		'glasses_halloween',
		'ssrbs_frank',
		'ssrbs_pump',
		'ssrbs_skull',
		'uneed_prop_ghostpumpkin',
		'uneed_prop_catcutehalloween',
		'uneed_prop_cookiehalloween',
		'uneed_prop_konmek1',
		'uneed_prop_meowpumpkin',
		'uneed_prop_konmek2',
		'uneed_prop_ass',
		'uneed_prop_assbeg',
		'uneed_prop_snowbear',
		'jarp_pob',
		'jarp_krasue',
		'jarp_krahang',
		'jarp_kumanthong',
		'jarp_nangrum',
		'jpx_pompompurin_standing',
		'jpx_kitty_standing',
		'jpx_cinnamoroll_standing',
		'jpx_bad_badtz_maru_standing',
		'jpx_pompompurin_plushie',
		'jpx_pochacco_plushie',
		'jpx_pochacco_chips',
		'jpx_kuromi_plushie',
		'jpx_kitty_plushie',
		'jpx_kitty_bag',
		'jpx_cinnamoroll_plushie',
		'jpx_cinnamoroll_bag',
		'jpx_kitty_umbrella',
		'jpx_pompompurin_dropping',
		'jpx_pochacco_hat',
		'jpx_my_melody_headwear',
		'jpx_my_melody_headband',
		'jpx_kuromi_headband',
		'jpx_kitty_headband2',
		'jpx_kitty_headband',
		'jpx_cinnamoroll_headwear',
		'jpx_cinnamoroll_drink',
		'jpx_kitty_headwear',
		'jpx_keroppi_dropping',
		'jpx_gudetama_dropping',
		'jpx_cinnamoroll_dropping',
		'jpx_pompompurin_ring',
		'jpx_pochacco_ring',
		'jpx_my_melody_ring',
		'jpx_kuromi_ring',
		'jpx_kitty_ring',
		'jpx_cinnamoroll_ring',
		'jpx_my_melody_bag',
		'jpx_pompompurin_doll',
		'jpx_pompompurin_bag',
		'jpx_pochacco_doll',
		'jpx_pochacco_backpack',
		'jpx_kuromi_wings',
		'jpx_kuromi_tail',
		'jpx_kitty_backpack',
		'jpx_cinnamoroll_backpack',
		'jpx_kitty_doll2',
		'jpx_kitty_doll',
		'jpx_keroppi_doll',
		'jpx_gudetama_doll2',
		'jpx_gudetama_doll',
		'jpx_kitty_fur',
		'jpx_pompompurin_moon',
		'uneed_prop_rambutansc_r',
		'uneed_prop_rambutan_l',
		'uneed_prop_rambutan_h',
		'uneed_prop_shiba_fig',
		'uneed_prop_shiba',
		'khaolaarm_no1_free_moodeng',
		'gold_bag_duck',
		'gold_hat_duck',
		'gold_shoeduck_l',
		'gold_shoeduck_r',
		'band_male_story',
		'band_female_story',
		'chonky_axolotl_head',
		'cute_duck_head',
		'parade_cats1',
		'parade_cats2',
		'parade_cats3',
		'parade_cats4',
		'sexycats1',
		'sexycats2',
		'sexycats3',
		'prop_bds01',
		'prop_bds02',
		'prop_bds03',
		'prop_bds04',
		'nitroboos_jubjub',
		'rune_wing',
		'wing_blackquadra',
		'wing_bluequadra',
		'wing_brownquadra',
		'wing_greenquadra',
		'wing_pinkquadra',
		'wing_whitequadra',
		'jub_wing',
		'jubwing_v2_blue',
		'jubwing_v2_green',
		'jubwing_v2_pink',
		'jubwing_v2_white',
		'jubwing_v2_yellow',
		'noone_hugcat_anim_fashions',
		'noone_pigwaddles_anim_fashions',
		'noone_heartbubble_anim_fashions',
		'noone_balloonpig_anim_fashions',
		'noone_redpandabackpack_anim_fashions',
		'noone_rabbitcarrot_anim_fashions',
		'noone_robotwing_anim_fashions',
		'noone_cuteghosts_anim_fashions',
		'manao_fashion_text1',
		'manao_fashion_text2',
		'manao_fashion_text3',
		'manao_fashion_text4',
		'cinnamonbag',
		'cinnamonhand',
		'cinnamonhead',
		'cinnamonshoeR',
		'cinnamonshoeL',
		'Rainbowcat',
		'sm_fashion_tiny_cow',
		'sm_fashion_tiny_pig',
		'sm_fashion_tiny_rabbit',
		'sm_fashion_tiny_cat',
		'sm_fashion_tiny_dog',
		'sm_fashion_tiny_unicorn',
		'font_1',
		'font_2',
		'font_3',
		'font_4',
		'font_5',
		'slotmachine_valentine_ch',
		'fashion_newbie',
		'fashion_newbies',
		'acc_bag_duck',
		'acc_hat_duck',
		'acc_shoeduck_l',
		'acc_shoeduck_r',
		'london_gacha_01_bag_1',
		'london_gacha_01_bag_2',
		'london_gacha_01_head_1',
		'london_gacha_01_upper_1',
		'london_gacha_01_upper_2',
		'london_gacha_01_upper_3',
		'un_fashion_v7_turtle',
		'un_fashion_v7_husky',
		'un_fashion_v7_backpack',
		'un_fashion_v7_golden',
		'un_fashion_v7_blues',
		'un_fashion_v7_catback',
		'london_gacha_02_bearbrick_black',
		'london_gacha_02_bearbrick_golden',
		'london_gacha_02_cat_incar',
		'london_gacha_02_carebear_yellow',
		'london_gacha_02_carebear_white',
		'london_gacha_02_carebear_pink',
		'london_gacha_02_carebear_blue',
		'acc_gang_armring_vip_evo',
		'acc_discord_boot_new_hks_evo',
		'aidenta_anya_fashion',
		'aidenta_anyadoll_fashion',
		'aidenta_backpack_fashion_x01',
		'aidenta_backpack_fashion_x02',
		'aidenta_cathat_fashion_x01',
		'aidenta_cathat_fashion_x02',
		'aidenta_bearbagx1_fashion',
		'aidenta_bearbagx2_fashion',
		'aidenta_bearbagx3_fashion',
		'aidenta_bearbagx4_fashion',
		'aidenta_bearbagx5_fashion',
		'aidenta_catwizx1_fashion',
		'aidenta_catwizx2_fashion',
		'aidenta_unicorn_bag',
		'aidenta_unicorn_horn',
		'aidenta_unicorn_icecream',
		'aidenta_unicorn_wings',
		'aidenta_unicorn_tails',
		'aidenta_unicorn_effect',
		'meow_sk3_gun01',
		'meow_sk3_gun02',
		'meow_sk3_elefant01',
		'meow_sk3_elefant02',
		'meow_sk3_water',
		'meow_sk3_waterbody',
		'BruniBody',
		'bb_cute01',
		'bb_cute02',
		'bb_cute03',
		'bb_cute06',
		'bb_cute07',
		'bb_cute11',
		'bb_cute12',
		'band_male_staff',
		'band_male_admin',
		'band_female_staff',
		'band_female_admin',
		'jpx_cinnamoroll_slippers',
		'jpx_little_doll_magic_circle',
		'sailor01',
		'sailor02',
		'sailor03',
		'ducky1',
		'ducky2',
		'ducky3',
		'ducky4',
		'ducky5',
		'ducky6',
		'ducky7',
	}
}
