
--- @class InfoItem
--- @field detail string รายละเอียดของไอเทม
--- @field where string[] แหล่งที่มาหรือสถานที่ที่พบ
--- @field rare number ระดับความหายาก
--- @field damage number ค่าความเสียหาย
--- @field listdamage number[] รายการค่าความเสียหาย
---

Infoitem = Infoitem or {}
Infoitem = {
    ['WEAPON_NIGHTSTICK'] = {
        detail = '',
        where = {},
        rare = 1,
        damage = 0,
        listdamage = { 40 },
    },
    ['WEAPON_SWITCHBLADE'] = {
        detail = '',
        where = {},
        rare = 1,
        damage = 0,
        listdamage = { 100 },
    },
    ['chromium'] = {
        detail = 'แร่ชนิดพิเศษจำเป็นต้องใช้เหล็กและไม้หลอมรวมกันจึงจะได้แร่ชนิดนี้มา',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = { },
    },
    ['pipe_repair'] = {
        detail = 'อุปกรณ์ซ่อมท่อน้ำ ท่อน้ำแตกยังมีอุปกรณ์ซ่อม น้ำตาแตกนี่ต้องใช้อะไรซ่อมน้า',
        where = {},
        rare = 1,
        damage = 0,
        listdamage = { },
    },
    ['electric_repair'] = {
        detail = 'electric_repair',
        where = {},
        rare = 1,
        damage = 0,
        listdamage = { },
    },
    ['aed'] = {
        detail = 'อุปกรณ์สำหรับชุบชีวิตเพื่อน สามารถใช้ชุบชีวิตได้ 1 ครั้งต่อ 1 ไอเท็ม',
        where = {'สภา', 'โต๊ะคราฟ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['aed_agency'] = {
        detail = 'อุปกรณ์ชุบชีวิต แต่ไม่สามารถชุบคนที่ตายจากใจขึ้นมาได้นะ สำหรับหน่วยงานเท่านั้น',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['pain_agency'] = {
        detail = 'สิ่งบรรเทาความเจ็บปวดจากอาการบาดเจ็บ แต่ถ้าเจ็บจากเค้า pain ก็คงช่วยไม่ได้ สำหรับหน่วยงานเท่านั้น',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['armor_agency'] = {
        detail = 'เกราะสำหรับปกป้องตัวเองจากดาเมจต่างๆ แต่ไม่สามารถปกป้องดาเมจที่เค้าสร้างไว้ในใจได้ สำหรับหน่วยงานเท่านั้น',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['pain_warzone'] = {
        detail = 'ผ้าพันแผลสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['armor_warzone'] = {
        detail = 'เกราะสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['aed_warzone'] = {
        detail = 'อุปกรณ์ชุบชีวิตสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['bandage'] = {
        detail = 'ผ้าพันแผลบรรเทาความเจ็บปวดได้เล็กน้อยแต่ถ้าแผลใหญ่ก็ทนหน่อยนะ ไม่สามารถบรรเทาความเจ็บปวดที่เค้าทิ้งไว้ให้ได้',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['pack_box'] = {
        detail = 'กล่องใส่อุปกรณ์สำหรับชุบชีวิตเพื่อน ข้างในจะประกอบด้วย AED หลายชิ้น',
        where = {'สภา', 'สวัสดิการ', 'โต๊ะคราฟ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['pain'] = {
        detail = 'อุปกรณ์สำหรับเพิ่มเลือด สามารถใช้เพิ่มเลือดได้ 1 ครั้งต่อ 1 ไอเท็ม',
        where = {'สภา', 'โต๊ะคราฟ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['pain_box'] = {
        detail = 'กล่องใส่อุปกรณ์สำหรับเพิ่มเลือด ข้างในจะประกอบไปด้วย painkiller หลายชิ้น',
        where = {'สภา', 'สวัสดิการ', 'โต๊ะคราฟ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['armor'] = {
        detail = 'อุปกรณ์สำหรับเพิ่มเกราะ สามารถใช้เพิ่มเกราะได้ 1 ครั้งต่อ 1 ไอเท็ม',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['armor_box'] = {
        detail = 'กล่องใส่อุปกรณ์สำหรับเพิ่มเกราะ ข้างในจะประกอบไปด้วย Armor หลายชิ้น',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['mre'] = {
        detail = 'อาหารบรรเทาความหิว แต่ไม่สามารถบรรเทาความคิดถึงที่มีให้คนเก่าได้ สำหรับหน่วยงานเท่านั้น',
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['burger'] = {
        detail = 'เบอร์เกอร์แสนอร่อยหาซื้อง่าย เพิ่มค่าความหิวได้ 10%',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['coke'] = {
        detail = 'เครื่องดื่มรสชาติดี มีความซ่า แบบ โคคาโคลา สามารถลดค่าความเครียดได้ 10%',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['milkshake'] = {
        detail = 'เครื่ื่องดื่มนมปั่นแสนสดชื่น ได้กลิ่นนมวัวจากเต้า ดิ่มแล้วสุขภาพดี สามารถลดความเครียดได้ 100%',
        where = {'โต๊ะคราฟอาหาร'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['tonkatsu'] = {
        detail = 'ข้าวหมูทอดสไตล์ญี่ปุ่น กลิ่นหอมของหมูทอดร้อนๆและข้าวญี่ปุ่นสุดนุ่มฟู สามารถลดความหิวได้ 100%',
        where = {'โต๊ะคราฟอาหาร'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['happymeal'] = {
        detail = 'ชุดแฮปปี้มีลแสนคุ้มค่า อิ่มแบบจุใจ สามารถลดทั้งค่าสมองและค่าความหิวได้ 100%',
        where = {'โต๊ะคราฟอาหาร'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },

    ['pork'] = {
        detail = 'เนื้อหมูสดใหม่ เกรดพรีเมี่ยม เนื้อฉ่ำจ๋าว ไม่ต่างจากเนื้อวัว',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['milk'] = {
        detail = 'นมโคสด 100% จากฟาร์ม คั้นสดๆจากแม่พันธุ์วัวชั้นเลิศ',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['radish'] = {
        detail = 'หัวไชเท้า ลูกโต สด สะอาด จากธรรมชาติปลอดภัยไร้ยาฆ่าแมลง',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['scallion'] = {
        detail = 'ต้นหอม พืชผักสมุนไพร สด สะอาด เต็มเปี่ยมไปด้วยคุณค่าทางโภชนาการ',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['duck'] = {
        detail = 'เนื้อเป็ดแท้ 100% โปรตีนสูงไม่มีวัตถุเจือปน',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['carrot'] = {
        detail = 'แครอท คุณภาพเยี่ยม มีวิตามิน และคุณประโยชน์มากมาย สด สะอาด ถูกหลักอนามัย',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['squid'] = {
        detail = 'ปลาหมึก คุณภาพดี ตัวใหญ่ สดใหม่จากท้องทะเล',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['urchin'] = {
        detail = 'ไข่หอยเม่น พันธุ์ดีจากน่านน้ำทะเล รสหวานไร้กลิ่นคาว คุณภาพเกรดประมูล',
        where = {'ฟาร์ม'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['fossil'] = {
        detail = 'ร่องรอยอารยธรรมจากยุคโบราณ มูลค่าสูง และ หายาก น้อยคนนักที่จะพบเจอ',
        where = {'ฟาร์ม'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['steel'] = {
        detail = 'เหล็กชั้นดี ที่ผ่านการคัดเลือกมาแล้ว เหมาะแก่การนำมาทำอาวุธ หรือ อุปกรณ์อย่างอื่นเป็นอย่างดี',
        where = {'ฟาร์ม'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['wood'] = {
        detail = 'ไม้คุณภาพชั้นเลิศ ผ่านขั้นตอนการแปรรูปมาอย่างประณีต ควรค่าแก่การนำมาสร้าง อุปกรณ์ ต่างๆ',
        where = {'ฟาร์ม'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },

    ['id_card'] = {
        detail = 'บัตรประชาชน บัตรยืนยันการเป็นประชาชนของเมือง เธอๆเราขอดูบัตรหน่อย',
        where = {'ของติดตัวผู้เล่นทุกคน'},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['money'] = {
        detail = 'ปัจจัยที่ 1 ในการดำรงชีวิตไม่สามารถขาดสิ่งนี้ไปได้เลยจริงๆ',
        where = {'หลายหลากแหล่ง'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['phone'] = {
        detail = 'มือถือคู่ใจไว้โทรหาหวานใจ ไอ้ตัวความรัก',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['black_money'] = {
        detail = 'สิ่งจำเป็นต่อการคราฟไอเท็มต่างๆ แต่ระวังนะเพราะมันคือสิ่งผิดกฎหมาย',
        where = {'ขายยา', 'กิจกรรมเมือง'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['discordboost'] = {
        detail = 'กล่องได้จะได้รับจากการที่ผู้เล่นช่วย  Boost Discord Server',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_box'] = {
        detail = 'ของขวัญต้อนรับเข้าสู่เมือง BUILD CITY หวังว่าผู้เล่นจะมีความสุขกับของที่ได้จากกล่องนี้ ',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_car'] = {
        detail = 'ของขวัญต้อนรับเข้าสู่เมือง BUILD CITY หวังว่าผู้เล่นจะมีความสุขกับของที่ได้จากกล่องนี้',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['gacha_support'] = {
        detail = 'ของขวัญเล็กๆน้อยๆที่ทางประเทศอยากมอบให้ผู้เล่น',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['gachapromote'] = {
        detail = 'แค่ผู้เล่นช่วย โปรโมท ประเทศ ผู้เล่นก็จะได้รับของสนับสนุนในส่วนนี้ไป มีของดีๆอยู่ข้างในด้วยนะ',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['gacha_farm'] = {
        detail = 'รางวัลคนขยันของมากมายให้ลุ้น แบบ ปึ้งงง ',
        where = {'งานฟาร์มรอบเมือง'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_fashion'] = {
        detail = 'แฟชั่นที่ผู้เล่นใหม่ทุกคนจะได้รับ นับว่าเป็นของขวัญจากทางประเทศ',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['mineral'] = {
        detail = 'แร่อันมีค่า ที่จะรวมแร่ต่างๆ ผสมกันออกมาจนเป็นแร่ชั้นดี',
        where = {'เหมือง'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },

    ['voltboard'] = {
        detail = 'ของผิดกฏหมายชิ้นส่วนหลักในการทำอุปกรณ์ต่างๆ หาได้ง่าย แต่คุณต้องใช้ความสามารถและฝีมือในการขับรถ',
        where = {'งานดำ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['cement'] = {
        detail = 'ของผิดกฏหมายชิ้นส่วนหลักในการทำอุปกรณ์ต่างๆ หาได้ง่าย แต่คุณต้องใช้ความสามารถและฝีมือในการขับรถ',
        where = {'งานดำ'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['cap_a'] = {
        detail = 'แคปซูล A สารสกัดชั้นเลิศในการผลิตยาผิดกฎหมาย',
        where = {'งานดำ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['cap_b'] = {
        detail = 'แคปซูล B สารสกัดชั้นรองในการผลิตยาผิดกฎหมาย',
        where = {'งานดำ'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['cap_c'] = {
        detail = 'แคปซูล C สารสกัดชั้นเริ่มต้นในการผลิตยาผิดกฎหมาย',
        where = {'งานดำ'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['cocaine'] = {
        detail = 'สิ่่งผิดกฎหมาย เป็นงานที่มีความเสี่ยง ต้องใช้ความสามารถ',
        where = {'งานดำ'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['heroin'] = {
        detail = 'สิ่่งผิดกฎหมาย เป็นงานที่มีความเสี่ยง ต้องใช้ความสามารถ',
        where = {'งานดำ'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['blueprint_poolcue'] = {
        detail = 'ไอเทมสำคัญในการคราฟอาวุธ ต้องมีติดตัวก่อนคราฟอาวุธทุกชนิด',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['gachatiktok'] = {
        detail = 'กาชาปองของดาวต๊อกๆ เพราะพวกเราคือนักคอนเทนท์',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['gachastreamer'] = {
        detail = 'กาชาปองของสตรีมเมอร์ตัวน้อย เราจะไปเป็นตัวโต๋ในวงการ',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['ticketpromote'] = {
        detail = 'ตั๋วใช้แลกของรางวัลพิเศษในโต๊ะคราฟ',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['vibraniumblue'] = {
        detail = '',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['vibraniumgreen'] = {
        detail = '',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['vibraniumred'] = {
        detail = '',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },

    ['repairkit'] = {
        detail = 'กล่องซ่อมรถ ใช้ซ่อมรถอย่างเดียวซ่อมใจไม่ได้นะ',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['lockpick'] = {
        detail = 'อุปกรณ์ในการงัดร้านค้า จำเป็นจะต้องมีฝีมือเบื้องต้นในการใช้ ไม่ใช่ว่าใครก็จะใช้งานมันได้',
        where = {'ในเมือง'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['fishingrod'] = {
        detail = 'เบ็ดตกปลา อุปกรณ์ในการทำงานประเภทหนึ่ง หาซื้อได้ในร้านค้าทั่วไป',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['bait'] = {
        detail = 'เหยื่อตกปลา อุปกรณ์จำเป็นในการใช้เป็นเหยื่อล่อปลา หาซื้อได้ทั่วไปตามร้านค้า',
        where = {'ร้านค้าทั่วไป'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['speaker'] = {
        detail = 'ลำโพง ใช้ในการเปิดเพลง สำหรับใครที่อยากบรรเทาความแบื่อจากการฟาร์มหรือจะเปิดไว้จีบสาวก็ยังได้',
        where = {'ร้านค้าทั่วไป'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },

    ['diamond'] = {
        detail = 'เพชร แร่เกรดสูงสุดภายในเมืองแร่ โอกาสหาเจอค่อนข้างยาก แต่ได้มาก็ถือว่าคุ้มค่ากับแรงที่เสียไป',
        where = {'เหมืองแร่'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['gold'] = {
        detail = 'แร่ทอง แร่ชั้นเลิศ เป็นที่ต้องการในตลาด อาจพบเจอได้ไม่ง่ายนัก แต่คุณจะต้องการมันอย่างแน่นอน',
        where = {'เหมืองแร่'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['silver'] = {
        detail = 'แร่เงิน แร่ที่พบได้ค่อนข้างบ่อย มูลค่าอาจไม่สูงมากนัก แต่เป็นแร่ที่ขาดไม่ได้ในการผลิตอุปกรณ์ต่างๆ',
        where = {'เหมืองแร่'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['copper'] = {
        detail = 'แร่ทองแดง แร่ขั้นเริ่มต้น พบได้ง่ายในเหมือง เนื่องจากพบได้มากจึงเป็นวัตถุดิบที่ใช้เยอะในการผลิตอย่างแน่นอน',
        where = {'เหมืองแร่'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['earth_powder'] = {
        detail = 'ผงดิน เป็นเศษผงที่ได้จากการแปรรูปแร่ภายในเหมือง แต่ภายในผงดินเหล่านี้ยังคงมีเศษแร่บางอย่างปะปนอยู่',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },

    ['voltvip'] = {
        detail = 'บัตรสิทธิพิเศษ สำหรับ ผู้ถือครอง สวัสดิการและสิทธิที่มากกว่าท่านอื่น บัตรอันมีค่าที่คุณไม่ควรพลาด',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ['key'] = {
        detail = 'กุญแจรถ ไอเท็มจำเป็นสำหรับเจ้าของรถ หากคุณขาดมันไปรถคันนั้นก็ไม่ต่างอะไรกับเหล็กก้อนนึง',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['voltcoin'] = {
        detail = 'เหรียญสำหรับคราฟไอเทมต่างๆ ในโต๊ะคราฟ',
        where = {'AFK'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['voltafk'] = {
        detail = 'เหรียญ AFK หาได้จากโซนเฉพาะ ใช้แลกของเอ็กซ์คลูซีฟในหมวด AFK',
        where = {'AFK'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['timestone'] = {
        detail = 'เหรียญ Online ได้จากการอยู่ภายในเมือง ใช้ในการแลกของต่างๆ',
        where = {'Online'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },

    ['weaponbox'] = {
        detail = 'กล่องตีอาวุธ วัตถุดิบหลัก ในการสร้างอาวุธ วัตถุดิบที่เหล่ายอดฝีมือจะต้องใช้อย่างแน่นอน',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['newbieweaponcard'] = {
        detail = 'บัตรตีอาวุธ สำหรับมือใหม่ ใช้ในการคราฟอาวุธเริ่มต้นสำหรับท่าน จุดเริ่มต้นของทุกๆอย่าง',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['reskincard'] = {
        detail = 'บัตรรีกิน บัตรสำหรับศัลยกรรม เสริมความสวยหล่อของท่าน ภายในบัตรใบเดียว',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['lady_gangcard'] = {
        detail = 'บัตรสำหรับสมาชิกแก๊ง เพื่อแสดงตัวตนในการเป็นสมาชิก และรับสิทธิพิเศษสำหรับสมาชิกแก๊งต่างๆ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['storm_gangcard'] = {
        detail = 'บัตรสำหรับสมาชิกแก๊ง เพื่อแสดงตัวตนในการเป็นสมาชิก และรับสิทธิพิเศษสำหรับสมาชิกแก๊งต่างๆ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['thunder_gangcard'] = {
        detail = 'บัตรสำหรับสมาชิกแก๊ง เพื่อแสดงตัวตนในการเป็นสมาชิก และรับสิทธิพิเศษสำหรับสมาชิกแก๊งต่างๆ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['registerfamily'] = {
        detail = 'บัตรลงทะเบียนครอบครัว มาสร้างครอบครัวไปด้วยกันดีกว่า',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['storm_gangregister'] = {
        detail = 'บัตรลงทะเบียนขึ้นแก๊ง บัตรเริ่มต้นในการก่อตั้งกลุ่มของคุณ และอาจเป็นจุดเริ่มต้นของความสนุกที่รอคุณอยู่ ',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['thunder_gangregister'] = {
        detail = 'บัตรลงทะเบียนขึ้นแก๊ง บัตรเริ่มต้นในการก่อตั้งกลุ่มของคุณ และอาจเป็นจุดเริ่มต้นของความสนุกที่รอคุณอยู่ ',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['lady_gangregister'] = {
        detail = 'บัตรลงทะเบียนขึ้นแก๊ง บัตรเริ่มต้นในการก่อตั้งกลุ่มของคุณ และอาจเป็นจุดเริ่มต้นของความสนุกที่รอคุณอยู่ ',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['lady_gangregister2'] = {
        detail = 'บัตรลงทะเบียนขึ้นแก๊ง บัตรเริ่มต้นในการก่อตั้งกลุ่มของคุณ และอาจเป็นจุดเริ่มต้นของความสนุกที่รอคุณอยู่ ',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['familycard'] = {
        detail = 'บัตรสำหรับสมาชิกครอบครัว เพื่อแสดงตัวตนในการเป็นสมาชิก และรับสิทธิพิเศษสำหรับสมาชิกครอบครัวต่างๆ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['invitecard'] = {
        detail = 'บัตรสำหรับใช้เข้าร่วม แก๊ง ครอบครัว ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['exitcard'] = {
        detail = 'บัตรสำหรับใช้ออกจาก แก๊ง ครอบครัว ',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['drill'] = {
        detail = 'ไอเทมที่จำเป็นในการงัดธนาคาร แต่งัดให้ตายก็ไม่เจอหัวใจเขาอยู่ดี',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['cutting'] = {
        detail = 'ไอเทมสำหรับตัดกุญแจมือ ตัดกุญแจมือแล้วอย่าลืมตัดเขาออกจากใจด้วยนะ',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {},
    },

    ['garden_fertilizer'] = {
        detail = 'นวัฒกรรมจากอนาคต ใช้เร่งการเจริญเติบโตของพืชผัก ชื่อว่า ปุ๋ย',
        where = {'ร้านค้าที่ Garden Center'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['garden_water_can'] = {
        detail = 'สิ่งประดิษฐ์จากชาวสวนชื่อว่า จอร์น ใช้สำหรับ รดน้ำต้นไม้ระวังให้ดีหากคุณไม่เติมน้ำให้เต็มอยู่เสมอมันจะใช้งานไม่ได้',
        where = {'ร้านค้าที่ Garden Center'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['pumpkin'] = {
        detail = 'ฟักทองจากความเหน็ดเหนื่อยของชาวสวน ขายได้ราคาดี',
        where = {'ปลูกผัก'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['strawberry'] = {
        detail = 'สตอร์เบอร์รี่ ผลไม้สุดน่ารัก ผลมีรสหวานอมเปรี้ยว ต้องให้ความรักถึงจะมีผลอวบสวย  ขายได้ราคาดี',
        where = {'งาน Grower'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['durain'] = {
        detail = 'ทุเรียน ราชาผลไม้เมืองไทย คุณคือ ชาวสวนที่มีความพยายามในการปลูกเป็นอย่างมากจึงได้รับมา ขายได้ราคาดี',
        where = {'งาน Grower'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['rare_pumpkin'] = {
        detail = 'ผลไม้สีฟ้า เป็นพืชผักพิเศษ ชาวสวนเคยเล่าว่า เป็นพืชผักที่มีฟ้าผ่าลงมาทำให้มีราคาสูงเพราะมีสารอาหารที่มากกว่าปกติ',
        where = {'งาน Grower'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['rare_strawberry'] = {
        detail = 'ผลไม้สีฟ้า เป็นพืชผักพิเศษ ชาวสวนเคยเล่าว่า เป็นพืชผักที่มีฟ้าผ่าลงมาทำให้มีราคาสูงเพราะมีสารอาหารที่มากกว่าปกติ',
        where = {'งาน Grower'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['rare_durain'] = {
        detail = 'ผลไม้สีฟ้า เป็นพืชผักพิเศษ ชาวสวนเคยเล่าว่า เป็นพืชผักที่มีฟ้าผ่าลงมาทำให้มีราคาสูงเพราะมีสารอาหารที่มากกว่าปกติ',
        where = {'งาน Grower'},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['epic_pumpkin'] = {
        detail = 'ผลไม้สายรุ้งต้องใช้ความตั้งใจและความพยายามในการปลูก มีข่าวลือว่า หากร้องเพลงให้พืชผักฟังจะออกผลเป็นผลไม้สายรุ้ง',
        where = {'งาน Grower'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['epic_strawberry'] = {
        detail = 'ผลไม้สายรุ้งต้องใช้ความตั้งใจและความพยายามในการปลูก มีข่าวลือว่า หากร้องเพลงให้พืชผักฟังจะออกผลเป็นผลไม้สายรุ้ง',
        where = {'งาน Grower'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['epic_durain'] = {
        detail = 'ผลไม้สายรุ้งต้องใช้ความตั้งใจและความพยายามในการปลูก มีข่าวลือว่า หากร้องเพลงให้พืชผักฟังจะออกผลเป็นผลไม้สายรุ้ง',
        where = {'งาน Grower'},
        rare = 3,
        damage = 0,
        listdamage = {},
    },

    ['blueprint_bottle'] = {
        detail = 'ไอเทมสำคัญในการคราฟอาวุธ ต้องมีติดตัวก่อนคราฟอาวุธทุกชนิด',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['blueprint_knuckle'] = {
        detail = 'ไอเทมสำคัญในการคราฟอาวุธ ต้องมีติดตัวก่อนคราฟอาวุธทุกชนิด',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['bolt_vipbox'] = {
        detail = 'กล่อง vip ที่จะอัพเกรดความสะดวกสบายเพิ่มให้คุณ',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ['radio'] = {
        detail = 'วิทยุสือสารแต่ไม่สือใจ ต่อให้สื่อได้เขาก็ไม่กลับมา อิอิ',
        where = {'โต๊ะคราฟ'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['WEAPON_BOTTLE'] = {
        detail = 'อาวุธสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {35},
    },
    ['WEAPON_POOLCUE'] = {
        detail = 'อาวุธสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้Y',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {25},
    },
    ['WEAPON_KNUCKLE'] = {
        detail = 'อาวุธสำหรับการฝึกซ้อมที่สนามฝึก ไม่สามารถนำออกนอกสนามฝึกได้',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {25},
    },

    ['WEAPON_POOLCUE_0'] = {
        detail = 'อาวุธไก่ เพราะคุณคือไก่ตัวใหม่ที่จะมาเฉิดฉายที่ BUILD CITY',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {2},
    },
    ['WEAPON_POOLCUE_1'] = {
        detail = 'อาวุธอัพเกรดจากไม้ไก่ เพราะคุณไม่ไก่อีกต่อไป',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {12},
    },
    ['WEAPON_POOLCUE_EXTRA'] = {
        detail = 'อาวุธอัพเกรดขั้น extra ตัวโต๋ระดับมาเฟีย',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {25},
    },

    ['WEAPON_BOTTLE_0'] = {
        detail = 'อาวุธไก่ เพราะคุณคือไก่ตัวใหม่ที่จะมาเฉิดฉายที่ BUILD CITY',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {10},
    },
    ['WEAPON_BOTTLE_1'] = {
        detail = 'อาวุธอัพเกรดจากปากฉลามไก่ เพราะคุณไม่ไก่อีกต่อไป',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {17},
    },
    ['WEAPON_BOTTLE_2'] = {
        detail = 'อาวุธอัพเกรดขั้น 2 อีกนิดนะคุณจะได้เป็นตัวโต๋ระดับมาเฟียแล้ว',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {25},
    },
    ['WEAPON_BOTTLE_EXTRA'] = {
        detail = 'อาวุธอัพเกรดขั้น extra ตัวโต๋ระดับมาเฟีย',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {35},
    },

    ['WEAPON_KNUCKLE_1'] = {
        detail = 'สนับเริ่มต้น หัดต่อยแบบเบบี๋ระดับดาเมจเหมือนโดนจิ้มแก้ม',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {10},
    },
    ['WEAPON_KNUCKLE_2'] = {
        detail = 'สนับอัพเกรดเวล 2 ไม่เบบี๋แล้วน้า',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {15},
    },
    ['WEAPON_KNUCKLE_3'] = {
        detail = 'สนับอัพเกรดเวล 3 นักต่อยตัวตึง',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {20},
    },
    ['WEAPON_KNUCKL_EXTRA'] = {
        detail = 'สนับ extra รุ่นโต๋ลงสนาม',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {25},
    },
    ['WEAPON_KNUCKLE'] = {
        detail = '',
        where = {''},
        rare = 5,
        damage = 0,
        listdamage = {25},
    },

    ['pipe_repair'] = {
        detail = '',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['electric_repair'] = {
        detail = '',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['membership'] = {
        detail = 'บัตรจำเป็นของนักฟามตัวตึง ระดับนี้เค้านั่งฟามกันชิวๆ',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['sardine'] = {
        detail = 'ปลาซาดีน ปลาหาง่ายตกง่ายราคาถูก',
        where = {''},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['mackerel'] = {
        detail = 'ปลาแมกเคอเรล จับไม่ยากราคาไม่แย่',
        where = {''},
        rare = 2,
        damage = 0,
        listdamage = {},
    },
    ['kingfish'] = {
        detail = 'ปลาคิงฟิช จับยากหน่อย แต่ราคาขายค่อนข้างสูงเลยทีเดียว ',
        where = {''},
        rare = 3,
        damage = 0,
        listdamage = {},
    },
    ['snapper'] = {
        detail = 'ปลาสแนปเปอร์ เจ้าปลาหายากราคาสูง',
        where = {''},
        rare = 4,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_carspeed7day'] = {
        detail = 'รถสปอร์ตเช่า 7 วันสำหรับผู้เล่นใหม่ให้คุณได้ทดลองเป็นนักซิ่งมืออยู่หลังพวงมาลัย หัวใจอยู่ข้างเธอ',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_car150kg3day'] = {
        detail = 'รถบรรทุกเช่า 3 วันสำหรับสร้างตัวจุดเริ่มต้นของการเป็นหัวแถวแห่งเมือง BUILD CITY',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['newplayer_car60kg'] = {
        detail = 'รถเริ่มต้นถาวรสำหรับผู้เล่นใหม่',
        where = {''},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ['garden_seed_pumpkin'] = {
        detail = 'เมล็ดพันธ์ฟักทอง',
        where = {'ร้านค้าที่ Garden Center'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['garden_seed_durian'] = {
        detail = 'เมล็ดพันธุ์ทุเรียน',
        where = {'งาน Grower'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ['garden_seed_strawberry'] = {
        detail = 'เมล็ดพันธุ์สตอร์เบอร์รี่',
        where = {'งาน Grower'},
        rare = 1,
        damage = 0,
        listdamage = {},
    },
    ["boostx2"] = {
        detail = "Boost Boost ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น  นึกอะไรไม่ออกนึกถึง Boost Boost",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box1hr"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box2hr"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box3hr"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box1day"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box3day"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["boostx2_box7day"] = {
        detail = "กล่องใส่ไอเทมที่จะทำให้คุณฟาร์มได้ของมากขึ้น",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["theflash"] = {
        detail = "สิ่งที่จะทำให้คุณฟาร์มไวขึ้นแบบสายฟ้าแลบ ไอเทมสำหรับลดระยะเวลาฟาร์ม แต่ไม่ได้ลดระยะห่างระหว่างคุณกับเขา",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["theflash_box1day"] = {
        detail = "กล่องใส่ไอเทมสำหรับลดระยะเวลาฟาร์ม ข้างในจะมีบัตรที่ทำให้คุณฟาร์มไวขึ้นแบบสายฟ้าแลบ",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["theflash_box3day"] = {
        detail = "กล่องใส่ไอเทมสำหรับลดระยะเวลาฟาร์ม ข้างในจะมีบัตรที่ทำให้คุณฟาร์มไวขึ้นแบบสายฟ้าแลบ",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["theflash_box7day"] = {
        detail = "กล่องใส่ไอเทมสำหรับลดระยะเวลาฟาร์ม ข้างในจะมีบัตรที่ทำให้คุณฟาร์มไวขึ้นแบบสายฟ้าแลบ",
        where = {},
        rare = 5,
        damage = 0,
        listdamage = {},
    },
    ["car_trade"] = {
        detail = "ถ้าคุณมีไอเทมนี้คุณจะสามารถมอบรถของคุณให้กับผู้อื่นได้ แต่ถ้าจะมอบหัวใจให้ใครต้องระวังดีๆนะ",
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ["fashion_trade"] = {
        detail = "ถ้าคุณมีไอเทมนี้คุณจะสามารถมอบแฟชั่นของคุณให้กับผู้อื่นได้  แต่ถ้าจะมอบหัวใจให้ใครต้องระวังดีๆนะ",
        where = {},
        rare = 05,
        damage = 0,
        listdamage = {},
    },
    ["trade_skin"] = {
        detail = "ถ้าคุณมีไอเทมนี้คุณจะสามารถมอบสกินอาวุธของคุณให้กับผู้อื่นได้ แต่ถ้าจะมอบหัวใจให้ใครต้องระวังดีๆนะ",
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
    ["titanium"] = {
        detail = "แร่ชนิดพิเศษไม่สามารถหาได้จากการขุดเหมืองปกติ จะต้องนำโครเมียมมาหลอมอีกที",
        where = {},
        rare = 0,
        damage = 0,
        listdamage = {},
    },
}